Iter9
Ostrovsky42/metric-alert pull request #10
Opened 2023-05-28 01:51 UTC by Ostrovsky42

2023-05-29 16:10 UTC, maxlyaptsev requested changes

2023-05-29 16:10 UTC, maxlyaptsev commented on cmd/server/config.go
> +		}
всю эту конструкцию можно заменить на одну строчку
```suggestion
    env.Parse(& cfg)
```

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/helpers/helpers.go
> +	body, err := io.ReadAll(reader)
не очень понял зачем читать весь бади в другую переменную, а потом анмаршалить, мы же можем сразу декодировать бади. Весь метод можно заменить на одну строчку (см json.Decode)

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/handlers/get_value.go
> +	metric.MType = chi.URLParam(r, "metric_type")
```suggestion
	metric.MType = chi.URLParam(r, _metricType)
```
лучше все подобные строки выносить в константы

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/storage/memstorage.go
> +func (m *MemStorage) GetMetric(metric entities.Metrics) (entities.Metrics, bool) {
в качестве ключа лучше все же использовать id, нет смысла ставить в зависимость целый объект, когда на самом деле нужен только айдишник

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/handlers/get_value.go
> +}
Можно реализовать stringer интерфейс например. Или сделать другой метод у структуры metric и избежать сложных условий  в, и без того перегруженной логикой, ручке

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/handlers/update.go
> +func (m MetricAlerts) UpdateMetricWithBody(w http.ResponseWriter, r *http.Request) {
```suggestion
func (m *MetricAlerts) UpdateMetricWithBody(w http.ResponseWriter, r *http.Request) {
```
лучше методы делать не для копии объекта, а по ссылке

2023-05-29 16:10 UTC, maxlyaptsev commented on cmd/server/app.go
> +	go a.fileStorage.Run()
если внутри не смогли сделать restore то никто ничего не заметит и сервис будет работать с пустым стреджом. Правильно ли запускать приложение в таком состоянии?

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/agent/agent.go
> +	}
здесь несколько раз происходит перекладывание данных в разные буферы. Это точно нужно, почему не использовать то что gzip имеет интерфейс Writer а Encoder принимает writer?

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/agent/agent.go
> +	zipped, err := zipData(data)
упаковку было бы уместней сделать в мидлваре

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/helpers/helpers.go
> +	err := encoder.Encode(data)
такие важные вещи лучше в хелперы не закрывать - текущий вариант через буфер посредник алоцирует много лишней памяти и используя хелпер это трудно заметить

2023-05-29 16:10 UTC, maxlyaptsev commented on internal/agent/helpers.go
> +	return &floatVal
создаем копию переменной и возвращаем на нее ссылку? Зачем, почему просто не брать ссылку переменной?

2023-05-29 16:10 UTC, maxlyaptsev commented on cmd/server/main.go
> +	log := zerolog.New(os.Stdout).With().Caller().Timestamp().Logger()
Логгер можно сделать глобальным, и иметь везде доступ к одному настроенному логеру, а не передавать его во все места

2023-05-31 21:47 UTC, Ostrovsky42 commented on internal/agent/helpers.go
> +	return &floatVal
Cannot take the address of 'float64(val)'
Хочу класть в структуру *float, но runtime.MemStats содержит поля в  uint64

2023-05-31 21:48 UTC, Ostrovsky42 commented on internal/agent/agent.go
> +	zipped, err := zipData(data)
разве мидлвары используются не только в обработчиках? не совсем понял что ты имеешь ввиду

2023-06-01 22:08 UTC, maxlyaptsev requested changes

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/agent/agent.go
> +	zipped, err := zipData(data)
нужно как-то декомпозитовать код чтобы его было легко читать, чтобы у разных пакетов бала своя определенная ответственность. Конечно, можно весь код наисать в один файл, но работать с таким кодом будет очень сложно
Еще код часто разделяют на пакет с бизнесл лоигкой и пакеты, которые не зависят  от логики приложения.
Например мидлвары можно спокойно таскать в разные проекты или даже вынести в pkg и импортировать в другие проекты. А вот импортировать агента будет сложно

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/agent/helpers.go
> +	return &floatVal
грязный хак, я понял. Лучше конечно найти более удачную структуру для хранения

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/agent/agent.go
> +	metrics        *[29]entities.Metrics
а если добавится еще метрика, поменяется тип? Почему вообще тип данных в структуре должен зависеть от количества данных?

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/storage/filestorage.go
> +	defer f.file.Close()
Что будет если вызывать Run несколько раз?
В контексте этого метода не ясно откуда взялся файл, зачем он нужен и зачем его закрывать, а значит можно легко поломать логику.
Предлагаю перенести в метод restore и открытие файла и  чтение и закрытие

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/storage/filestorage.go
> +	}
NewFileRecorder  вызывается при старте приложения. И сразу открывает файл, но ничего с этим не делает.  В будущем мы можем изменить логику приложения и не восстанавливать данные. Но открытый файл будет висеть все время
Почему не сделать метод у этой структуры, который откроет файл и обработает?

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/storage/filestorage.go
> +	for {
это не ответсвенность стореджа делать сохранение по расписанию. Сторедж может сохранять данные и отдавать. А вот логику его периодического вызова лучше вынести - это больше похоже на модель воркера

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/handlers/get_value.go
> +	w.Write(metric.ByteValue())
есть и другие способы записать данные в ответ (см первый спринт) без лишних методов. Например так:
```suggestion
fmt.Fprintf(w, "%v",  metric.Value)
```

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/entities/metrics.go
> +func (m Metrics) ByteValue() []byte {
метод лишний, в целом в go не стоит делать методы которые приобразовывают один тип в другой

2023-06-01 22:08 UTC, maxlyaptsev commented on internal/agent/helpers.go
> +func setMetricArray() *[29]entities.Metrics {
есть же метод по сбору метрик. Зачем понадобился второй?  Надо отрефакторить и пересмотреть структуру хранения чтобы код не дублировался

2023-06-02 15:07 UTC, maxlyaptsev approved these changes

2023-06-02 15:44 UTC, merged