Iter23
Ostrovsky42/metric-alert pull request #24
Opened 2023-09-18 20:48 UTC by Ostrovsky42

2023-09-22 12:35 UTC, arttet requested changes

2023-09-22 12:35 UTC, arttet commented on internal/server/config/config.go
> +func readJSONConfig(path string) (Config, error) {
It should be a pointer

2023-09-22 12:35 UTC, arttet commented on internal/crypto/symmetric/simmetric.go
> +func (s Symmetric) Encrypt(plainText []byte) ([]byte, []byte, error) {
Why do you copy this struct every time?

2023-09-22 12:35 UTC, arttet commented on internal/crypto/asymmetric/encryptor.go
> +	if block == nil || block.Type != "PUBLIC KEY" {
This is a magic string

2023-09-25 22:54 UTC, Ostrovsky42 commented
Я все еще не понял почему я получил при первом коммите, но не получаю при последующих, хотя покрытие отображается по ссылке указанной в логах codecov
https://app.codecov.io/github/Ostrovsky42/metric-alert/commit/87261f3f67df9617adb08fb53f7e2e0da370d1f9

2023-09-26 15:25 UTC, arttet commented
> Я все еще не понял почему я получил при первом коммите, но не получаю при последующих, хотя покрытие отображается по ссылке указанной в логах codecov https://app.codecov.io/github/Ostrovsky42/metric-alert/commit/87261f3f67df9617adb08fb53f7e2e0da370d1f9

main: https://app.codecov.io/github/Ostrovsky42/metric-alert
iter23: https://app.codecov.io/github/Ostrovsky42/metric-alert/tree/iter23

2023-09-26 15:40 UTC, arttet approved these changes

2023-09-26 15:40 UTC, arttet commented on internal/agent/config/config.go
> +		return Config{}, err
If I were you, I would return a pointer

2023-09-26 15:40 UTC, arttet commented on internal/crypto/asymmetric/decryptor.go
> +const PrivateKey = "PRIVATE KEY"
It would be better if we can configure this value

2023-09-26 15:40 UTC, arttet commented on cmd/server/app.go
> const templatePath = "internal/server/html/templates/info_page.html"

You can use an embedded filesystem.

2023-09-26 15:40 UTC, arttet commented on cmd/server/app.go
Yes, it won't work if you change a working dir. So, you should use an embedded filesystem.

2023-10-01 22:20 UTC, merged